/************* BATCH CONSTANTS *************/

export const BATCH_ROLLBACK = ' BATCH_ROLLBACK';
export const BATCH_TOP_HOSPITALS = ' BATCH_TOP_HOSPITALS';
export const BATCH_TOP_AGENTS = 'BATCH_TOP_AGENTS';
export const BATCH_TOP_DOCTORS = 'BATCH_TOP_DOCTORS';
